apiVersion: v1alpha1
kind: Setting
metadata:
  name: halo-plugin-auto-backup-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: select
          label: 按天/小时
          name: timeUnit
          validation: required
          value: 'DAY'
          options:
            - label: 小时
              value: HOUR
            - label: 天
              value: DAY
        - $formkit: select
          label: 时间间隔
          name: interval
          validation: required|Number
          value: 3
          action: /apis/autobackup.wangwenzhu.cn/v1alpha1/config-interval
          requestOption:
            method: GET
        - $formkit: select
          label: 备份最大保存数量
          name: maxBackupCount
          validation: required
          value: 5
          options:
            - label: 1
              value: 1
            - label: 2
              value: 2
            - label: 3
              value: 3
            - label: 4
              value: 4
            - label: 5
              value: 5